Update Script

diff --git a/ADM-MANAGER-ALPHA/Modulos/menu_inst b/ADM-MANAGER-ALPHA/Modulos/menu_inst
--- a/ADM-MANAGER-ALPHA/Modulos/menu_inst
+++ b/ADM-MANAGER-ALPHA/Modulos/menu_inst
@@ -47,9 +47,14 @@ echo -e "$portas"
 
 #MEU IP
 fun_ip () {
+if [[ -e /etc/MEUIPADM ]]; then
+IP="$(cat /etc/MEUIPADM)"
+else
 MEU_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
 MEU_IP2=$(wget -qO- ipv4.icanhazip.com)
 [[ "$MEU_IP" != "$MEU_IP2" ]] && IP="$MEU_IP2" || IP="$MEU_IP"
+echo "$MEU_IP2" > /etc/MEUIPADM
+fi
 }
 
 #ETHOOL SSH
@@ -117,20 +122,22 @@ fun_squid  () {
 echo -e "$barra\n\033[1;32m $(fun_trans "INSTALADOR SQUID ADM-ULTIMATE")\n$barra"
 fun_ip
 echo -ne " $(fun_trans "Confirme seu ip")"; read -p ": " -e -i $IP ip
-echo -e " $(fun_trans "Agora Escolha as Portas que Deseja No Squid")"
-echo -e " $(fun_trans "Escolha As Portas Em Ordem Sequencial Exemplo: 80 8080 8799 3128")"
-echo -ne " $(fun_trans "Digite as Portas:") "; read portasx
-totalporta=($portasx)
-unset PORT
-   for((i=0; i<${#totalporta[@]}; i++)); do
-        [[ $(mportas|grep "${totalporta[$i]}") = "" ]] && {
-        echo -e "\033[1;33m $(fun_trans "Porta Escolhida:")\033[1;32m ${totalporta[$i]} OK"
-        PORT+="${totalporta[$i]}\n"
+echo -e "$barra"
+echo -e "\033[1;31m $(fun_trans "Agora Escolha as Portas que Deseja No Squid")"
+echo -e "\033[1;31m $(fun_trans "Escolha As Portas Em Ordem Sequencial Exemplo:")\033[1;32m 80 8080 8799 3128 \033[1;37m"
+echo -e "$barra"
+echo -ne "\033[1;31m $(fun_trans "Digite a Porta"): \033[1;37m" && read DPORT
+tput cuu1 && tput dl1
+TTOTAL=($DPORT)
+    for((i=0; i<${#TTOTAL[@]}; i++)); do
+        [[ $(mportas|grep "${TTOTAL[$i]}") = "" ]] && {
+        echo -e "\033[1;33m $(fun_trans "Porta Escolhida:")\033[1;32m ${TTOTAL[$i]} OK"
+        PORT="$PORT ${TTOTAL[$i]}"
         } || {
-        echo -e "\033[1;33m $(fun_trans "Porta Escolhida:")\033[1;31m ${totalporta[$i]} FAIL"
+        echo -e "\033[1;33m $(fun_trans "Porta Escolhida:")\033[1;31m ${TTOTAL[$i]} FAIL"
         }
    done
-  [[ "$(echo -e $PORT)" = "" ]] && {
+  [[  -z $PORT ]] && {
   echo -e "\033[1;31m $(fun_trans "Nenhuma Porta Valida Foi Escolhida")\033[0m"
   return 1
   }
@@ -278,23 +285,32 @@ rm /tmp/portz
 fun_dropbear () {
  [[ -e /etc/default/dropbear ]] && {
  echo -e "$barra\n\033[1;32m $(fun_trans "REMOVENDO DROPBEAR")\n$barra"
+ fun_bar "service dropbear stop &"
  fun_bar "apt-get remove dropbear -y"
  echo -e "$barra\n\033[1;32m $(fun_trans "Dropbear Removido")\n$barra"
  [[ -e /etc/default/dropbear ]] && rm /etc/default/dropbear
  return 0
  }
 echo -e "$barra\n\033[1;32m $(fun_trans "INSTALADOR DROPBEAR ADM-ULTIMATE")\n$barra"
-echo -e " $(fun_trans "POR PADRÃO, DROPBEAR USA A PORTA 443")\033[1;37m"
+echo -e "\033[1;31m $(fun_trans "Selecione Portas Validas em Ordem Sequencial:")\033[1;32m 22 80 81 82 85 90\033[1;37m"
 echo -e "$barra"
-   [[ $(mportas|grep 443) != "" ]] && {
-   echo -e "\033[1;31m $(fun_trans "PORTA 443 EM USO")\033[1;37m"
-   echo -e "\033[1;31m $(fun_trans "LIBERE ELA, E TENTE NOVAMENTE")\033[1;37m"
-   echo -e "$barra"
-   return 1
-   }
+echo -ne "\033[1;31m $(fun_trans "Digite a Porta"): \033[1;37m" && read DPORT
+tput cuu1 && tput dl1
+TTOTAL=($DPORT)
+    for((i=0; i<${#TTOTAL[@]}; i++)); do
+        [[ $(mportas|grep "${TTOTAL[$i]}") = "" ]] && {
+        echo -e "\033[1;33m $(fun_trans "Porta Escolhida:")\033[1;32m ${TTOTAL[$i]} OK"
+        PORT="$PORT ${TTOTAL[$i]}"
+        } || {
+        echo -e "\033[1;33m $(fun_trans "Porta Escolhida:")\033[1;31m ${TTOTAL[$i]} FAIL"
+        }
+   done
+  [[  -z $PORT ]] && {
+  echo -e "\033[1;31m $(fun_trans "Nenhuma Porta Valida Foi Escolhida")\033[0m"
+  return 1
+  }
 sysvar=$(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/      //' | grep -o Ubuntu)
-shells=$(cat /etc/shells|grep "/bin/false")
-[[ ! ${shells} ]] && echo -e "/bin/false" >> /etc/shells
+[[ ! $(cat /etc/shells|grep "/bin/false") ]] && echo -e "/bin/false" >> /etc/shells
 [[ "$sysvar" != "" ]] && {
 echo -e "Port 22
 Protocol 2
@@ -326,12 +342,18 @@ echo -e "${cor[2]} $(fun_trans "Instalando dropbear")"
 echo -e "$barra"
 fun_bar "apt-get install dropbear -y"
 echo -e "$barra"
-touch /etc/dropbear/banner
+touch /etc/bannerssh
 echo -e "${cor[2]} $(fun_trans "Configurando dropbear")"
-echo -e "NO_START=0" > /etc/default/dropbear
-echo -e 'DROPBEAR_EXTRA_ARGS="-p 443"' >> /etc/default/dropbear
-echo -e 'DROPBEAR_BANNER="/etc/dropbear/banner"' >> /etc/default/dropbear
-echo -e "DROPBEAR_RECEIVE_WINDOW=65536" >> /etc/default/dropbear
+cat <<EOF > /etc/default/dropbear
+NO_START=0
+DROPBEAR_EXTRA_ARGS="VAR"
+DROPBEAR_BANNER="/etc/bannerssh"
+DROPBEAR_RECEIVE_WINDOW=65536
+EOF
+for dpts in $(echo $PORT); do
+sed -i "s/VAR/-p $dpts VAR/g" /etc/default/dropbear
+done
+sed -i "s/VAR//g" /etc/default/dropbear
 } || {
 echo -e "Port 22
 Protocol 2
@@ -362,18 +384,24 @@ UsePAM yes" > /etc/ssh/sshd_config
 echo -e "${cor[2]} $(fun_trans "Instalando dropbear")"
 echo -e "$barra"
 fun_bar "apt-get install dropbear -y"
-touch /etc/dropbear/banner
+touch /etc/bannerssh
 echo -e "$barra"
 echo -e "${cor[2]} $(fun_trans "Configurando dropbear")"
-echo -e "NO_START=0" > /etc/default/dropbear
-echo -e 'DROPBEAR_EXTRA_ARGS="-p 443"' >> /etc/default/dropbear
-echo -e 'DROPBEAR_BANNER="/etc/dropbear/banner"' >> /etc/default/dropbear
-echo -e "DROPBEAR_RECEIVE_WINDOW=65536" >> /etc/default/dropbear
+cat <<EOF > /etc/default/dropbear
+NO_START=0
+DROPBEAR_EXTRA_ARGS="VAR"
+DROPBEAR_BANNER="/etc/bannerssh"
+DROPBEAR_RECEIVE_WINDOW=65536
+EOF
+for dpts in $(echo $PORT); do
+sed -i "s/VAR/-p $dpts VAR/g" /etc/default/dropbear
+done
+sed -i "s/VAR//g" /etc/default/dropbear
 }
 fun_eth
 service ssh restart > /dev/null 2>&1
 service dropbear restart > /dev/null 2>&1
-echo -e "$barra\n${cor[3]} $(fun_trans "Seu dropbear foi configurado com sucesso")\n$barra"
+echo -e "${cor[3]} $(fun_trans "Seu dropbear foi configurado com sucesso")\n$barra"
 mportas > /tmp/portz
 while read portas; do
 [[ $portas = "" ]] && break
@@ -431,7 +459,7 @@ fi
 coleta_variaveis () {
 echo -e " $(fun_trans "Responda as perguntas para iniciar a instalacao")"
 echo -e " $(fun_trans "Responda corretamente")"
-echo -e "\033[1;33m$(fun_trans "Primeiro precisamos do ip de sua maquina, este ip esta correto?")\033[0m"
+echo -e "\033[1;33m $(fun_trans "Primeiro precisamos do ip de sua maquina, este ip esta correto?")\033[0m"
 fun_ip
 echo -ne " $(fun_trans "Confirme seu ip")"; read -p ": " -e -i $IP ip
 echo -e "$barra\n\033[1;33m$(fun_trans "Qual porta voce deseja usar?")\033[0m\n$barra"
